all:
	g++ -o myfirst.out myfirst.cpp
	g++ -o carrots.out carrots.cpp
	g++ -o getinfo.out getinfo.cpp
	g++ -o sqrt.out sqrt.cpp
	g++ -o outfunc.out outfunc.cpp
	g++ -o convert.out convert.cpp
	g++ -o convert.out convert.cpp
	for n in 1 2 3 4 5 6 7 ; do \
		g++ -o 2_$$n.out 2_$$n.cpp ; \
	done
clean:
	@rm -f *.out