all:
	g++ -o file.out file1.cpp coordin.h file2.cpp
	g++ -o autoscp.out autoscp.cpp
	g++ -o external.out external.cpp support.cpp
	g++ -o twofile.out twofile1.cpp twofile2.cpp
	g++ -o static.out static.cpp
	g++ -o newplace.out newplace.cpp
	g++ -o usenmsp.out usenmsp.cpp namesp.h namesp.cpp
	g++ -o 9_1.out 9_1.cpp golf.h golf.cpp
	g++ -o 9_2.out 9_2.cpp

clean:
	@rm -f *.out