all:
	g++ -o arrayone.out arrayone.cpp
	g++ -o strings.out strings.cpp
	g++ -o instr1.out instr1.cpp
	g++ -o instr2.out instr2.cpp
	g++ -o instr3.out instr3.cpp
	g++ -o numstr.out numstr.cpp
	g++ -o strtype1.out strtype1.cpp
	g++ -o strtype2.out strtype2.cpp
	g++ -o strtype3.out strtype3.cpp
	g++ -o strtype4.out strtype4.cpp
	g++ -o structur.out structur.cpp
	g++ -o assgn_st.out assgn_st.cpp
	g++ -o arrstruc.out arrstruc.cpp
	g++ -o address.out address.cpp
	g++ -o pointer.out pointer.cpp
	g++ -o init_ptr.out init_ptr.cpp
	g++ -o use_new.out use_new.cpp
	g++ -o arraynew.out arraynew.cpp
	g++ -o addpntrs.out addpntrs.cpp
	g++ -o ptrstr.out ptrstr.cpp
	g++ -o newstrct.out newstrct.cpp
	g++ -o delete.out delete.cpp
	g++ -o mixtypes.out mixtypes.cpp
	g++ -o choices.out choices.cpp
	for n in 1 2 3 4 5 6 7 8 9 10 ; do \
		g++ -o 4_$$n.out 4_$$n.cpp ; \
	done
clean:
	@rm -f *.out