all:
	g++ -o forloop.out forloop.cpp
	g++ -o num_test.out num_test.cpp
	g++ -o express.out express.cpp
	g++ -o formore.out formore.cpp
	g++ -o forstr1.out forstr1.cpp
	g++ -o plus_one.out plus_one.cpp
	g++ -o block.out block.cpp
	g++ -o forstr2.out forstr2.cpp
	g++ -o equal.out equal.cpp
	g++ -o compstr1.out compstr1.cpp
	g++ -o compstr2.out compstr2.cpp
	g++ -o while.out while.cpp
	g++ -o waiting.out waiting.cpp
	g++ -o dowhile.out dowhile.cpp
	g++ -o textin1.out textin1.cpp
	g++ -o textin2.out textin2.cpp
	g++ -o textin3.out textin3.cpp
	g++ -o textin4.out textin4.cpp
	g++ -o nested.out nested.cpp
	for n in 1 2 3 4 5 6 7 8 9 10 ; do \
		g++ -o 5_$$n.out 5_$$n.cpp ; \
	done
clean:
	@rm -f *.out